//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaABM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class categoria
    {
        public categoria()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int IdCategoria { get; set; }
        [Required]
        public string Nombre { get; set; }
    
        public virtual ICollection<producto> producto { get; set; }
    }
}
